### ISSUE TITLE
Volume can't be set by MPRIS control.

### ISSUE THREAD

**Issue by bernimoses** [emersion/mpris-service#2]
I've used the player.js example and added a initial volume at line 22 "player.volume = 0.5;".

My shell extension (Media player indicator) shows the volume, but if i change it the service crashes:

```
/opt/test/node_modules/mpris-service/index.js:281
			next();
			^
TypeError: undefined is not a function
    at iface.addProperty.setter (/opt/test/node_modules/mpris-service/index.js:281:4)
    at ServiceInterface.setProperty (/opt/test/node_modules/mpris-service/node_modules/dbus/lib/service_interface.js:142:14)
    at null.<anonymous> (/opt/test/node_modules/mpris-service/node_modules/dbus/lib/service_object.js:55:14)
    at ServiceInterface.call (/opt/test/node_modules/mpris-service/node_modules/dbus/lib/service_interface.js:108:17)
    at null.<anonymous> (/opt/test/node_modules/mpris-service/node_modules/dbus/lib/service.js:19:14)
    at emit (events.js:118:17)
    at /opt/test/node_modules/mpris-service/node_modules/dbus/lib/dbus.js:25:16
```

I think there is a bug in "node-dbus" as well which i've fixed: https://github.com/Shouqun/node-dbus/pull/102

**Comment by bernimoses** [comment]
Should be fixed now: https://github.com/Shouqun/node-dbus/pull/111
