### ISSUE TITLE
mpris-service 2.0 fails because of JSBI.BigInt with Webpack

### ISSUE THREAD

**Issue by martpie** [emersion/mpris-service#23]
on Electron 4.0.6 (Node 10.11), I have the following error when using `mpris-service@2.0.0`:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: JSBI.BigInt is not a function
    at Object../node_modules/dbus-next/lib/marshallers.js (/home/pierre/Documents/museeks/dist/main/webpack:/node_modules/dbus-next/lib/marshallers.js:267:1)
    at __webpack_require__ (/home/pierre/Documents/museeks/dist/main/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/dbus-next/lib/marshall.js (/home/pierre/Documents/museeks/dist/main/webpack:/node_modules/dbus-next/lib/marshall.js:5:21)
    at __webpack_require__ (/home/pierre/Documents/museeks/dist/main/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/dbus-next/lib/message.js (/home/pierre/Documents/museeks/dist/main/webpack:/node_modules/dbus-next/lib/message.js:2:18)
    at __webpack_require__ (/home/pierre/Documents/museeks/dist/main/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/dbus-next/index.js (/home/pierre/Documents/museeks/dist/main/webpack:/node_modules/dbus-next/index.js:7:17)
    at __webpack_require__ (/home/pierre/Documents/museeks/dist/main/webpack:/webpack/bootstrap:19:1)
    at Object../node_modules/mpris-service/dist/index.js (/home/pierre/Documents/museeks/dist/main/webpack:/node_modules/mpris-service/dist/index.js:7:14)
    at __webpack_require__ (/home/pierre/Documents/museeks/dist/main/webpack:/webpack/bootstrap:19:1)
```

Most probably caused by @acrisci's `node-dbus-next`. I am not sure what could cause this as this version of node support BigInt.

This is reproducible like that:

```bash
git clone https://github.com/martpie/museeks.git
cd museeks
git checkout mpris-service-2
npm install
npm run modules:rebuild
npm run build # npm run dev to watch
npm run museeks:debug
```

**Comment by acrisci** [comment]
This is probably a webpack configuration error. I can try to help but my knowledge of webpack is limited. I can reproduce this on https://github.com/martpie/museeks/pull/475 .

I can get it to work on [the webpack quick start demo](https://github.com/electron-userland/electron-webpack-quick-start) just fine with electron 4.0.1.

I can't see anything immediately wrong with mpris-service or dbus-next. JSBI.BigInt should definitely be a function from what I see there.

The mpris-service library will always use JSBI, so node version isn't an issue.

I've had to do weird things for webpack before to workaround their bugs, so I'll try some stuff later.

**Comment by martpie** [comment]
mmmh, ok, I'll check how GPMDP did it 👍

**Comment by martpie** [comment]
I can confirm this is Webpack specific. I am doing researches with either `require().default` is the way to go or not

**Comment by martpie** [comment]
I think I found something interesting. The `mjs` file of `jsbi` seems to be imported instead of the commonJS one. Still investigating.

**Comment by martpie** [comment]
```
  resolve: {
    alias: {
      jsbi: path.resolve(__dirname, 'node_modules', 'jsbi', 'dist', 'jsbi-cjs.js')
    }
  },
```

seems to fix it.

**Comment by acrisci** [comment]
Ok great. If you learn more and want to do a doc update or fix on the libraries that would be good. Otherwise it looks like just a normal weird webpack error.

**Comment by martpie** [comment]
I will close this. I still have two issues:

- I still have a `Error: unknown bus address` that I am not sure how to fix. `mpris-service@1.1.4` worked well 🤔 
- it also throws `UnhandledPromiseRejectionWarning: Unhandled promise rejections are deprecated. Inthe the future, promise rejections that are not handled will terminate the Node..js process with a non-zero code`, I will submit a patch for `mpris-service` or `node-dbus-next`.

**Comment by acrisci** [comment]
@martpie thanks a lot, I just used this on an implementation for another player (nuclear). I will add this fix to the documentation.

**Comment by Rapiz1** [comment]
Any update on this? Why will this happen?
I have the same issue but the solution above did not work.
